# Generated by Django 2.0.3 on 2018-12-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_price',
            fields=[
                ('publisher_name', models.CharField(default='', max_length=256, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('price_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Price_type')),
            ],
        ),
    ]
