# Generated by Django 2.0.3 on 2018-12-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0002_image_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(default='', max_length=256, primary_key=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('price_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Price_type')),
            ],
        ),
        migrations.RemoveField(
            model_name='image_price',
            name='price_type',
        ),
        migrations.DeleteModel(
            name='Image_price',
        ),
    ]
