# Generated by Django 2.0.3 on 2018-12-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0003_auto_20181210_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher',
            new_name='publisher_id',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
