# Generated by Django 2.0.3 on 2018-12-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0006_publisher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publisher',
            new_name='Publisher_price',
        ),
    ]
