# Generated by Django 2.0.3 on 2018-12-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0007_auto_20181210_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher_price',
            name='rate',
        ),
    ]
