# Generated by Django 2.0.3 on 2018-12-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0008_remove_publisher_price_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(default='', max_length=256)),
                ('publisher_group', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='publisher_price',
            name='publisher_id',
        ),		
        migrations.AddField(
            model_name='publisher_price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='publisher_price',
            name='print_medium',
            field=models.ForeignKey(default='PAPER', on_delete=django.db.models.deletion.CASCADE, to='eStore.Print_medium'),
        ),
        migrations.AddField(
            model_name='publisher_price',
            name='publisher_price_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher_price',
            name='publisher',
            field=models.ForeignKey(default=11, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='eStore.Publisher'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='publisher_price',
            name='publisher_name',
        ),
        migrations.AlterUniqueTogether(
            name='publisher_price',
            unique_together={('publisher', 'print_medium', 'price_type')},
        ),
    ]
