# Generated by Django 2.0.3 on 2018-12-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0009_auto_20181211_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='moulding_size',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
