# Generated by Django 2.0.3 on 2018-12-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0010_cart_item_moulding_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stretch',
            fields=[
                ('stretch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=2000)),
                ('type', models.CharField(blank='', default='', max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('price_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Price_type')),
            ],
        ),
    ]
