# Generated by Django 2.0.3 on 2018-12-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0011_stretch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='voucher',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='product_product_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Product_product_tag'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='stretch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Stretch'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='stretch_size',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='product_product_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Product_product_tag'),
        ),
    ]
