# Generated by Django 2.0.3 on 2018-12-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0012_auto_20181227_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='image_height',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='image_width',
            field=models.DecimalField(decimal_places=0, default=16, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_items',
            name='image_height',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_items',
            name='image_width',
            field=models.DecimalField(decimal_places=0, default=16, max_digits=3),
            preserve_default=False,
        ),
    ]
