# Generated by Django 2.0.3 on 2018-12-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0013_auto_20181227_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='moulding_size',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='stretch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Stretch'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='stretch_size',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
