# Generated by Django 2.0.3 on 2018-12-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0014_auto_20181227_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='eStore.Cart'),
            preserve_default=False,
        ),
    ]
