# Generated by Django 2.1.4 on 2019-01-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0016_auto_20190105_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
