# Generated by Django 2.1.4 on 2019-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0019_moulding_applies_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
