# Generated by Django 2.1.4 on 2019-01-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0021_state_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.State')),
            ],
        ),
        migrations.CreateModel(
            name='Pin_code',
            fields=[
                ('pin_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.City')),
            ],
        ),
    ]
