# Generated by Django 2.1.4 on 2019-01-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0023_auto_20190107_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.City')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pin_code',
            unique_together={('pin_code', 'city')},
        ),
    ]
