# Generated by Django 2.1.4 on 2019-01-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0026_auto_20190107_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Promotion')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='promotion',
        ),
        migrations.AddField(
            model_name='cart',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Voucher'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Promotion'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Promotion'),
        ),
        migrations.AlterUniqueTogether(
            name='promotion_product',
            unique_together={('promotion', 'product')},
        ),
    ]
