# Generated by Django 2.1.4 on 2019-01-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0029_auto_20190109_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_staus',
            new_name='cart_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_staus',
            new_name='order_status',
        ),
    ]
