# Generated by Django 2.1.4 on 2019-01-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0031_auto_20190115_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin_city_state_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluk', models.CharField(max_length=500, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Country')),
                ('pin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Pin_code')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.State')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pin_city_state_country',
            unique_together={('pin_code', 'city', 'taluk', 'state', 'country')},
        ),
    ]
