# Generated by Django 2.1.4 on 2019-01-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0032_auto_20190116_1201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pin_city_state_country',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pin_city_state_country',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pin_city_state_country',
            name='country',
        ),
        migrations.RemoveField(
            model_name='pin_city_state_country',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='pin_city_state_country',
            name='state',
        ),
        migrations.AlterUniqueTogether(
            name='pin_code',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pin_code',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order_billing',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='order_shipping',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='user_billing_address',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='user_shipping_address',
            name='pin_code',
        ),
        migrations.DeleteModel(
            name='Pin_city_state_country',
        ),
        migrations.DeleteModel(
            name='Pin_code',
        ),
    ]
