# Generated by Django 2.1.4 on 2019-01-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0033_auto_20190116_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin_city_state_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluk', models.CharField(max_length=500, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Pin_code',
            fields=[
                ('pin_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.City')),
            ],
        ),
        migrations.AddField(
            model_name='pin_city_state_country',
            name='pin_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Pin_code'),
        ),
        migrations.AddField(
            model_name='pin_city_state_country',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.State'),
        ),
        migrations.AddField(
            model_name='order_billing',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Pin_code'),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Pin_code'),
        ),
        migrations.AddField(
            model_name='user_billing_address',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Pin_code'),
        ),
        migrations.AddField(
            model_name='user_shipping_address',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Pin_code'),
        ),
        migrations.AlterUniqueTogether(
            name='pin_code',
            unique_together={('pin_code', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='pin_city_state_country',
            unique_together={('pin_code', 'city', 'taluk', 'state', 'country')},
        ),
    ]
