# Generated by Django 2.1.4 on 2019-01-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0035_auto_20190116_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
