# Generated by Django 2.1.4 on 2019-01-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0036_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(default='TESTCODE', max_length=20),
            preserve_default=False,
        ),
    ]
