# Generated by Django 2.1.4 on 2019-01-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0037_voucher_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='vouncher_disc_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vouncher_disc_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
