# Generated by Django 2.1.4 on 2019-01-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0038_auto_20190119_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher_user',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher_user',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher_user',
            name='used_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
