# Generated by Django 2.1.4 on 2019-01-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0039_auto_20190119_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='vouncher_disc_amount',
            new_name='voucher_disc_amount',
        ),
    ]
