# Generated by Django 2.1.4 on 2019-01-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0040_auto_20190120_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='item_sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='item_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='item_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='item_sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='item_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='item_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
