# Generated by Django 2.1.4 on 2019-01-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0041_auto_20190124_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_disc_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='item_disc_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
