# Generated by Django 2.1.4 on 2019-01-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0044_auto_20190124_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vouncher_disc_amount',
            new_name='voucher_disc_amount',
        ),
    ]
