# Generated by Django 2.1.4 on 2019-01-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0046_auto_20190126_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=600, null=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Profile_group'),
        ),
    ]
