# Generated by Django 2.1.4 on 2019-01-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0047_auto_20190126_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=4000)),
                ('msg_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('response', models.CharField(blank=True, default='', editable=False, max_length=4000)),
                ('resp_datetime', models.DateTimeField(editable=False, null=True)),
                ('reponded_by', models.CharField(blank=True, default='', editable=False, max_length=30)),
            ],
        ),
    ]
