# Generated by Django 2.1.4 on 2019-01-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0048_contact_us'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
