# Generated by Django 2.1.4 on 2019-02-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0049_auto_20190130_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_number_by_month',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('month_year', models.CharField(max_length=6)),
                ('current_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order_billing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
