# Generated by Django 2.1.4 on 2019-02-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0052_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_image',
            name='status',
            field=models.CharField(default='INI', max_length=3),
            preserve_default=False,
        ),
    ]
