# Generated by Django 2.1.4 on 2019-02-08 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0053_user_image_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame_promotion',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('discount_type', models.CharField(max_length=10)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Ecom_site')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion_frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Frame_promotion')),
                ('moulding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eStore.Moulding')),
            ],
        ),
        migrations.AlterField(
            model_name='user_image',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eStore.Cart_item'),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='status',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='promotion_frame',
            unique_together={('frame_promotion', 'moulding')},
        ),
    ]
