# Generated by Django 2.1.4 on 2019-02-09 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0054_auto_20190208_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_image',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='user_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.User_image'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='user_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.User_image'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eStore.Ecom_site'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Voucher'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='acrylic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Acrylic'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Board'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eStore.Cart'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='moulding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Moulding'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='mount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Mount'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='print_medium',
            field=models.ForeignKey(default='PAPER', on_delete=django.db.models.deletion.PROTECT, to='eStore.Print_medium'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Product'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Promotion'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='stretch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Stretch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eStore.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Shipper'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Shipping_method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Shipping_status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eStore.Ecom_site'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Voucher'),
        ),
        migrations.AlterField(
            model_name='order_billing',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.User_billing_address'),
        ),
        migrations.AlterField(
            model_name='order_billing',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='eStore.Order'),
        ),
        migrations.AlterField(
            model_name='order_billing',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eStore.Ecom_site'),
        ),
        migrations.AlterField(
            model_name='order_billing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='acrylic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Acrylic'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Board'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='moulding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Moulding'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='mount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Mount'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eStore.Order'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='print_medium',
            field=models.ForeignKey(default='PAPER', on_delete=django.db.models.deletion.PROTECT, to='eStore.Print_medium'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Product'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Promotion'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='stretch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Stretch'),
        ),
        migrations.AlterField(
            model_name='order_shipping',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.User_shipping_address'),
        ),
        migrations.AlterField(
            model_name='order_shipping',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order_shipping_status_log',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Order'),
        ),
        migrations.AlterField(
            model_name='order_shipping_status_log',
            name='order_shipping_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Shipping_status'),
        ),
    ]
