# Generated by Django 2.1.4 on 2019-02-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0055_auto_20190209_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
