# Generated by Django 2.1.4 on 2019-02-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0056_promotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='frame_promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Frame_promotion'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='frame_promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Frame_promotion'),
        ),
    ]
