# Generated by Django 2.1.4 on 2019-02-12 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eStore', '0057_auto_20190209_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, default='', max_length=40)),
                ('voucher_disc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.IntegerField(null=True)),
                ('wishlist_sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wishlist_disc_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wishlist_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wishlist_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('wishlist_status', models.CharField(blank=True, default='AC', max_length=2)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eStore.Ecom_site')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist_item',
            fields=[
                ('wishlist_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_disc_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moulding_size', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('print_medium_size', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mount_size', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('board_size', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('acrylic_size', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('stretch_size', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('image_width', models.DecimalField(decimal_places=0, max_digits=3)),
                ('image_height', models.DecimalField(decimal_places=0, max_digits=3)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('acrylic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Acrylic')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Board')),
                ('frame_promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Frame_promotion')),
                ('moulding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Moulding')),
                ('mount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Mount')),
                ('print_medium', models.ForeignKey(default='PAPER', on_delete=django.db.models.deletion.PROTECT, to='eStore.Print_medium')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Product')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Promotion')),
                ('stretch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Stretch')),
                ('user_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.User_image')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eStore.Wishlist')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wishlist_item',
            unique_together={('wishlist_item_id', 'wishlist')},
        ),
    ]
