# Generated by Django 2.1.4 on 2019-02-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0058_auto_20190212_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attribute',
            name='value',
            field=models.CharField(max_length=2000),
        ),
    ]
