# Generated by Django 2.1.4 on 2019-02-14 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eStore', '0059_auto_20190213_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, max_length=30)),
                ('address_1', models.CharField(blank=True, max_length=600, null='')),
                ('address_2', models.CharField(blank=True, default='', max_length=600)),
                ('city', models.CharField(blank=True, default='', max_length=600)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('gst_number', models.CharField(blank=True, default='', max_length=600)),
                ('tax_id', models.CharField(blank=True, default='', max_length=600)),
                ('country', models.ForeignKey(default='IND', on_delete=django.db.models.deletion.PROTECT, to='eStore.Country')),
                ('pin_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.Pin_code')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile_group',
            name='discount_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='business_profile',
            name='profile_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eStore.Profile_group'),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eStore.State'),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
