# Generated by Django 2.1.4 on 2019-02-19 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0060_auto_20190214_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_cost_slabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('slab_to', models.DecimalField(decimal_places=2, max_digits=12)),
                ('flat_shipping_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='address_1',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='city',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='state',
            field=models.ForeignKey(default='KARNATAKA', on_delete=django.db.models.deletion.PROTECT, to='eStore.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
