# Generated by Django 2.1.4 on 2019-02-21 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0061_auto_20190219_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business_profile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
