# Generated by Django 2.1.4 on 2019-02-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0063_auto_20190224_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='aspect_ratio',
            field=models.DecimalField(decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_type',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='orientation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
