# Generated by Django 2.1.4 on 2019-02-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0064_auto_20190227_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
