# Generated by Django 2.1.4 on 2019-02-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eStore', '0065_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_words',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
